swagger: '2.0'
info:
  version: 1.0.0
  title: EpiOpera API Documentation
  description: EpiOpera API Documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:8080
basepath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /user:
    get:
      tags:
        - Utenti
      summary: Get all users in system
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Utente'
    post:
      tags:
        - Utenti
      summary: Post a new user
      parameters:
        - name: body
          in: body
          description: Body of user post API
          required: true
          schema:
            $ref: '#/definitions/Utente'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Utente'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /user/{username}:
    delete:
      tags:
        - Utenti
      summary: Deletes a user by username
      parameters:
        - name: username
          in: path
          description: Username of user to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid username
        '404':
          description: User not found
  /posts:
    get:
      tags:
        - Post
      summary: Get all posts in system
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
  /post/id/{id}:
    get:
      tags: 
        - Post
      summary: Get post by id
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
  /post/user/{username}:
    get: 
      tags:
        - Post
      summary: Get posts by user
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
  /post/segnala/{id}:
    put:
      tags:
        - Post
      summary: Flag a post by Id
      parameters:
        - name: id
          in: path
          description: Id of post to flag
          required: true
          schema:
            type: number
      responses:
        '200':
          description: OK
          schema: 
            $ref: '#/definitions/Post'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /post/valuta: 
    put:
      tags:
        - Post
      summary: Evaluate a post
      parameters:
        - name: body
          in: body
          description: Body of a post put API
          required: true
          schema:
            properties:
              id: 
                type: number
              username: 
                type: string
              valutazione:
                type: number
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /post/modifica:
    put:
      tags:
        - Post
      summary: Edit a post
      parameters:
        - name: body
          in: body
          description: Body of a post put API
          required: true
          schema:
            properties: 
              id: 
                type: number
              username:
                type: string
              titolo:
                type: string
              testo:
                type: string
              media:
                type: string
              tag:
                type: array
                items:
                  type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /post/salvaNeiFavoriti:
    put:
      tags:
        - Post
      summary: Save a post
      parameters:
        - name: body
          in: body
          description: Body of a post put API
          required: true
          schema:
            properties:
              id: 
                type: number
              username: 
                type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /post:
    post:
      tags:
        - Post
      summary: Post a new user
      parameters:
        - name: body
          in: body
          description: Body of post post API
          required: true
          schema:
            $ref: '#/definitions/Post'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Post'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /post/{id}:
    delete:
      tags:
        - Post
      summary: Deletes a post by id
      parameters:
        - name: id
          in: path
          description: Id of post to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid post id
        '404':
          description: Post not found
  /commento_post:
    post:
      tags:
        - Commenti Post
      summary: Post a new post comment
      parameters:
        - name: body
          in: body
          description: Body of post comment post API
          required: true
          schema:
            $ref: '#/definitions/Commento_Post'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Commento_Post'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /commento_post/{id_post}:
    get:
      tags:
        - Commenti Post
      summary: Get post comments by association Id
      parameters:
        - name: id_post
          in: path
          description: Association Id of post comment to get
          required: true
          schema:
            type: number
      responses:
        '400':
          description: Invalid association id
        '404':
          description: Comment not found
  /commento_post/{id}:
    delete:
      tags:
        - Commenti Post
      summary: Deletes a post comment by id
      parameters:
        - name: id
          in: path
          description: Id of post comment to delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid comment id
        '404':
          description: Comment not found
  /commento_profilo:
    post: 
      tags:
        - Commenti Profilo
      summary: Post a new profile comment
      parameters:
        - name: body
          in: body
          description: Body of a profile comment post API
          required: true
          schema:
            $ref: '#definitions/Commento_Profilo'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#definitions/Commento_Profilo'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /commento_profilo/{profilo_commentato}:
    get:
      tags:
        - Commenti Profilo
      summary: Get profile comments by name of commented profile
      parameters:
        - name: profilo_commentato
          in: path
          description: Name of commented profile
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid profile name
        '404':
          description: Profile not found
  /commento_profilo/{id}:
    delete:
      tags:
        - Commenti Profilo
      summary: Deletes a profile comment by Id
      parameters:
        - name: id
          in: path
          description: Id of profile comment to delete
          required: true
          schema:
            type: number
      responses:
        '400':
          description: Invalid comment Id
        '404': 
          description: Comment not found

definitions:
  Utente:
    required:
      - username
    properties:
      username:
        type: string
      email:
        type: string
        example: user@something.domain
      password:
        type: string
      iconaNSFW:
        type: boolean
        default: false
      bannerNSFW:
        type: boolean
        default: false
      lingua:
        type: string
        enum:
          - italiano
          - inglese
      nsfw:
        type: string
        enum:
          - 'no'
          - blur
          - 'yes'
      utenti_seguiti:
        type: array
        items:
          type: number
      post_favoriti:
        type: array
        items:
          type: number
  Post:
    required:
      - id
    properties:
      id:
        type: number
      titolo:
        type: string
      data:
        type: string
      testo:
        type: string
      media:
        type: string
      tag:
        type: array
        items:
          type: string
      punteggio_post:
        type: number
        default: 0
      segnalato:
        type: boolean
        default: 0
      numero_commenti:
        type: number
        default: 0
      associato_a_contest:
        type: array
        items:
          type: number
      creatore_post:
        type: string
  Commento_Post:
    required:
      - id
    properties:
      id:
        type: number
      id_post:
        type: number
      data:
        type: string
      testo:
        type: string
      punteggio_commento:
        type: number
        default: 0
      segnalato:
        type: boolean
        default: false
      creatore_commento:
        type: string
  Commento_Profilo:
    required:
      - id
    properties:
      id:
        type: number
      profilo_commentato:
        type: string
      titolo:
        type: string
      data:
        type: string
      testo: 
        type: string
      punteggio_commento:
        type: number
        default: 0
      segnalato:
        type: boolean
        default: false
      creatore_commento:  
        type: string
  Valutazione:
    required:
      - id
        username
        valutazione
    properties:
      id:
        type: number
      username:
        type: string
      valutazione:
        type: number